import React from "react";
import axios from "axios";

function wordList() {
    return [
        "Family",
        "Freedom",
        "Security",
        "Loyalty",
        "Intelligence",
        //"Connection",
        "Creativity",
        //"Humanity",
        "Success",
        "Respect",
        //"Invention",
        "Diversity",
        //"Generosity",
        "Integrity",
        //"Finesse",
        "Love",
        "Openness",
        //"Religion",
        "Order",
        //"Advancement",
        "Playfulness",
        "Forgiveness",
        //"Excitement",
        //"Change",
        //"Goodness",
        //"Involvement",
        //"Faith",
        "Wisdom",
        "Beauty",
        //"Caring",
        "Growth",
        //"Endurance",
        "Honesty",
        "Adventure",
        "Kindness",
        //"Teamwork",
        //"Career",
        "Communication",
        "Learning",
        "Excellence",
        "Innovation",
        //"Quality",
        //"Commonality",
        //"Contribution",
        "Spirituality",
        "Strength",
        //"Entertainment",
        "Wealth",
        "Unity",
        "Curiosity",
    ];
}

export default wordList;
